name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Latest Version
        id: version
        run: |
          LATEST_VERSION=$(curl -s https://hub.docker.com/v2/repositories/dataquad123/dataquad-prod-userregister/tags/ | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          
          if [ -z "$LATEST_VERSION" ]; then
            NEW_VERSION="1.0.0"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_VERSION"
            PATCH=$((PATCH + 1))

            # If PATCH reaches 10, increase MINOR and reset PATCH
            if [ "$PATCH" -ge 10 ]; then
              PATCH=0
              MINOR=$((MINOR + 1))
            fi

            # If MINOR reaches 10, increase MAJOR and reset MINOR + PATCH
            if [ "$MINOR" -ge 10 ]; then
              MINOR=0
              MAJOR=$((MAJOR + 1))
            fi

            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi

          echo "IMAGE_TAG=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t dataquad123/dataquad-prod-userregister:${{ env.IMAGE_TAG }} .
          docker tag dataquad123/dataquad-prod-userregister:${{ env.IMAGE_TAG }} dataquad123/dataquad-prod-userregister:latest

      - name: Push Docker Image
        run: |
          docker push dataquad123/dataquad-prod-userregister:${{ env.IMAGE_TAG }}
          docker push dataquad123/dataquad-prod-userregister:latest

      - name: Delete Old Images (Keep Only Last 10)
        run: |
          OLD_TAGS=$(curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} "https://hub.docker.com/v2/repositories/dataquad123/dataquad-prod-userregister/tags/" \
            | jq -r '.results[].name' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V | head -n -10)

          for TAG in $OLD_TAGS; do
            curl -X DELETE -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} "https://hub.docker.com/v2/repositories/dataquad123/dataquad-prod-userregister/tags/$TAG/"
          done
